package com.beidian.beidiannonxinling.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.beidian.beidiannonxinling.db.LineData;

import com.beidian.beidiannonxinling.db.LineDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lineDataDaoConfig;

    private final LineDataDao lineDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lineDataDaoConfig = daoConfigMap.get(LineDataDao.class).clone();
        lineDataDaoConfig.initIdentityScope(type);

        lineDataDao = new LineDataDao(lineDataDaoConfig, this);

        registerDao(LineData.class, lineDataDao);
    }
    
    public void clear() {
        lineDataDaoConfig.clearIdentityScope();
    }

    public LineDataDao getLineDataDao() {
        return lineDataDao;
    }

}
